language: java
deploy:
  provider: heroku
  api_key:
    secure: bVR0hQj9IgwvC0UpEHa6FNvOB47W0iyazMWqm0hzPmn1iJsnWXNv3e5n55AQeHeWGUZ9xwPf2UPYXjJ+PaphesFTu0zUcvRovyI1kXc6HbyAjPw8nowBRlrVsQOLh+FRUZG0oUSVZFih00oDyrjRcoJlbAMaSUITA711URZ7CItzLDjLEiNBZpYcslN55sQl+OefVBHaOjSbuCs5axBBqBPf2oIxz0DrlVu89xsv/Lu0VreEHiuWcmCHadcuaanuNmrqa4qqRNKPzEovnotOtUcIkyZUZRchwMaSieDV+qT1D8gd+kw66FKGwmnE1M+gY8V8KdRoza+VBP0JtrZpJI+Buk9IvNR1dIXGzW3DmttG73lGBwaV10c1l9Fidt9WRlOxZtBMWjGdNYIAGeRRjkjWJXi+1xUTR5Bs4aZlFit+x5gfTEifWeNyz3h2I6mLufmxduUgQARfusdcJDqcDOCADCkSOinhxXXmWTrPB5INukEV2Psk9msic2baX0YcAyX+bmexcU6xHa8NCTqbDoesJWI8m4ap2p+sXS0Sc9QrWzEIOKsHDhqed1J3KVVDmjTmujSOTcohdADLp+IYQ3vGJZ1rVDZZt3BhjtlfuWt1MR8m25ucWznbUlRXm2K7veEXt8j5krldAC5Qr5F2edBD1f05Z4V3X4hrVK50shs=
  app: my-exercise-diary
  on: development
  skip_cleanup: true